In [97]:
import pandas as pd
df=pd.read_csv("/content/sample_data/data.csv", encoding='latin1')

df["total sales"] = df["Quantity"] * df["UnitPrice"]

print("\nFirst 5 rows of 'Quantity', 'UnitPrice', and 'total sales':")
print(df[['Quantity', 'UnitPrice', 'total sales']].head())

First 5 rows of 'Quantity', 'UnitPrice', and 'total sales':
   Quantity  UnitPrice  total sales
0       6.0       2.55        15.30
1       6.0       3.39        20.34
2       8.0       2.75        22.00
3       6.0       3.39        20.34
4       6.0       3.39        20.34

In [98]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total sales
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6.0,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8.0,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6.0,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34

In [99]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,total sales
238346,557937,85132C,CHARLIE AND LOLA FIGURES TINS,1.0,6/23/2011 15:30,5.79,NaN,United Kingdom,5.79
238347,557937,DOT,DOTCOM POSTAGE,1.0,6/23/2011 15:30,157.81,NaN,United Kingdom,157.81
238348,557937,22303,COFFEE MUG APPLES DESIGN,6.0,6/23/2011 15:30,2.55,NaN,United Kingdom,15.30
238349,557937,22210,WOOD STAMP SET BEST WISHES,6.0,6/23/2011 15:30,0.83,NaN,United Kingdom,4.98
238350,557937,22892,SET OF SAL,NaN,NaN,NaN,NaN,NaN,NaN

In [100]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 238351 entries, 0 to 238350
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    238351 non-null  object
 1   StockCode    238351 non-null  object
 2   Description  237453 non-null  object
 3   Quantity     238350 non-null  float64
 4   InvoiceDate  238350 non-null  object
 5   UnitPrice    238350 non-null  float64
 6   CustomerID   171623 non-null  float64
 7   Country      238350 non-null  object
 8   total sales  238350 non-null  float64
dtypes: float64(4), object(5)
memory usage: 16.4+ MB

In [101]:
df.shape

(238351, 9)

In [102]:
df.drop_duplicates(inplace=True)

In [103]:
df["total sales"]

0          15.30
1          20.34
2          22.00
3          20.34
4          20.34
           ...
238346      5.79
238347    157.81
238348     15.30
238349      4.98
238350       NaN
Name: total sales, Length: 236397, dtype: float64

In [104]:
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
df["Month"] = df["InvoiceDate"].dt.month_name()

In [105]:
df["Month"]

0         December
1         December
2         December
3         December
4         December
            ...
238346        June
238347        June
238348        June
238349        June
238350         NaN
Name: Month, Length: 236397, dtype: object

In [107]:
print(df["total sales"].sum())

4251779.290999999